spring:
  application:
    name: Practice Feign Application

  data:
    mongodb:
      database: coin
      port: 27017

server:
  port: 8082

gecko:
  api:
    url: https://api.coingecko.com/api/v3

restTemplate:
  readTimeout: 10000
  connectTimeout: 3000

feign:
  hystrix:
    enabled: false

logging:
  level:
    root: INFO

---

spring:
  profiles:
    active: development

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: INFO
    org.apache.http.wire: DEBUG
    httpclient.wire: DEBUG
    org.apache.tomcat.util.http: DEBUG
    org.springframework.web.servlet: DEBUG
    sun.net.www.protocol.http: DEBUG