spring:
  application:
    name: Practice Feign Application

  data:
    mongodb:
      database: catalog
      port: 27017

server:
  port: 8082

gecko:
  api:
    url: https://api.coingecko.com/api/v3/

feign:
  hystrix:
    enabled: false


---

spring:
  profiles:
    active: development

server:
  port: ${SERVER_PORT:8082}